### ISSUE TITLE
适配flutter web

### ISSUE THREAD

**Issue by uniquejava** [OpenFlutter/flutter_oktoast#54]
Hello, 安卓和iOS都非常好用。是否考虑适配flutter web。

目前web环境下弹出的是一个小黑框， 看不见文字。 如下：

![oktoast](https://user-images.githubusercontent.com/1049271/78205060-d2aea500-74cd-11ea-954e-1fc97150450a.gif)

Thank you very much.

**Comment by CaiJingLong** [comment]
Hi, I will try it, if it is determined that there is a problem, I will try to fix it.

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/78651918-94611d80-78f3-11ea-9699-04c16a6079da.png)

I use the example of `OKToast`.

This should be caused by the different default colors of textStyle in android, iOS and web.

![image](https://user-images.githubusercontent.com/14145407/78652139-e73ad500-78f3-11ea-82d2-5bb1b15a6d71.png)

![image](https://user-images.githubusercontent.com/14145407/78652159-f1f56a00-78f3-11ea-834d-d11d26516851.png)

Next steps:
1. Define TextStyle on OKToast, and define colors in style.
2. The textStyle of the showToast method will override the style of OKToast, so you need to add a color to the textStyle of the showToast method.
